DO
        IF KEY STATE(KEY LEFT) THEN : PRINT "LEFT!" : ENDIF
        IF KEY STATE(KEY RIGHT) THEN : PRINT "RIGHT!" : ENDIF
        IF KEY STATE(KEY UP) THEN : PRINT "UP!" : ENDIF
        IF KEY STATE(KEY DOWN) THEN : PRINT "DOWN!" : ENDIF
    LOOP
